### ISSUE TITLE
Connect Ionic to Angular frontend

### ISSUE THREAD

**Issue by jacobbishop1000** [jacobbishop1000/video-crime-miner#40]
Need this to complete the tech stack and possibly to connect Angular to Node controller

**Comment by ejperezz** [comment]
https://ionicframework.com/docs/intro/cdn#:~:text=For%20adding%20Ionic%20to%20an,Angular%20CLI%27s%20ng%20add%20feature.&text=This%20will%20add%20the%20necessary,as%20add%20the%20styles%20needed.
