### ISSUE TITLE
Write tests for AWS layer files

### ISSUE THREAD

**Issue by jacobbishop1000** [jacobbishop1000/video-crime-miner#49]
Right now many tests we have are empty due to refactoring [this pull request](https://github.com/jacobbishop1000/video-crime-miner/pull/48). We need to re-write some comprehensive Jest tests with proper mocking of AWS for our AWS layer, and write ones for new modules as well. Use `videoFaceUtils.test.ts` as an example

**Comment by isaacmckinney** [comment]
started working on tests for rekog, sns, and sqs code with mock clients on branch 'video-rekognition'

**Comment by isaacmckinney** [comment]
/node_modules/test/AWS Layer/snsClient.test.ts on branch 'video-rekognition' has passing tests for /node_modules/src/AWS Layer/snsClient.ts

**Comment by isaacmckinney** [comment]
/node_modules/test/AWS Layer/sqsClient.test.ts on branch 'video-rekognition' has passing tests for functions: createQueue, getQueueUrl, and getQueueAttributes in /node_modules/src/AWS Layer/sqsClient.ts

**Comment by isaacmckinney** [comment]
/node_modules/test/AWS Layer/sqsClient.test.ts on branch 'video-rekognition' has passing tests for function: setQueueAttributes in /node_modules/src/AWS Layer/sqsClient.ts

**Comment by jacobbishop1000** [comment]
@isaacmckinney how is this coming along?

**Comment by isaacmckinney** [comment]
/node_modules/test/AWS Layer/Rekognition/videoLabelUtils.test.ts on branch 'video-rekognition' has passing tests for all functions in /node_modules/src/AWS Layer/Rekognition/videoLabelUtils.ts

**Comment by isaacmckinney** [comment]
created pull request to add new tests to main branch.

Once approval is given to merge, this issue can be closed.
